# Config file for [Air](https://github.com/gofiber/recipes/blob/master/air/.air.linux.conf)

root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g src/router/router.go --pd --parseInternal --output docs; go build -o ./build/goto ./src/main.go"
bin = "./build/goto"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules", "docs"]
exclude_file = []
delay = 1000 # ms
stop_on_error = true
kill_delay = 500 # ms